// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/my-list": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/detail/:type/:id": {
    params: {
      "type": string;
      "id": string;
    };
  };
  "/watch/:type/:id": {
    params: {
      "type": string;
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/search" | "/discover" | "/my-list" | "/settings" | "/detail/:type/:id" | "/watch/:type/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/my-list.tsx": {
    id: "routes/my-list";
    page: "/my-list";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/detail.$type.$id.tsx": {
    id: "routes/detail.$type.$id";
    page: "/detail/:type/:id";
  };
  "routes/watch.$type.$id.tsx": {
    id: "routes/watch.$type.$id";
    page: "/watch/:type/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/discover": typeof import("./app/routes/discover.tsx");
  "routes/my-list": typeof import("./app/routes/my-list.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/detail.$type.$id": typeof import("./app/routes/detail.$type.$id.tsx");
  "routes/watch.$type.$id": typeof import("./app/routes/watch.$type.$id.tsx");
};